name: check-kb4it-version

on:
  push:
    branches: [ master ]    # choose your branch
    # paths: ["docs/**"]  # optional: run ONLY if specific directory changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # Install pipx
      - name: Install pipx
        run: pip install pipx --user

      # Install requirements
      - name: Install requirements
        run: pip install -r requirements.txt

      # Install KB4IT
      - name: Install kb4it
        run: pipx install . --force

      # Execute KB4IT
      - name: Run kb4it
        run: kb4it -v

      # Deploy the generated website
      #~ - name: Upload artifact
        #~ uses: actions/upload-pages-artifact@v3
        #~ with:
          #~ path: ./site
