name: check-kb4it-version

on:
  push:
    branches: [ master ]    # choose your branch
    # paths: ["docs/**"]  # optional: run ONLY if specific directory changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Check out repository
        uses: actions/checkout@v4

      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      # Install setuptools
      - name: Install setuptools
        run: pip install --upgrade setuptools

      # Install requirements
      - name: Install requirements
        run: pip install -r requirements.txt

      # 3. Install kb4it
      - name: Install kb4it
        run: python setup.py install --user

      # 4. Execute kb4it
      - name: Run kb4it
        run: kb4it -v

      # OPTIONAL: deploy the generated website
      #~ - name: Upload artifact
        #~ uses: actions/upload-pages-artifact@v3
        #~ with:
          #~ path: ./site
